// scripts/generate-icons.mjs
// ---------------------------------------------------------------------------
// Single source of the app icon (phase 6d). Writes:
//   public/icon.svg                  rounded icon (favicon, manifest "any")
//   public/icons/icon-192.png        install icon
//   public/icons/icon-512.png        install icon
//   public/icons/icon-maskable-512.png  full-bleed, art inside the ~80 %
//                                       safe zone (OS masks the shape)
//
// Rasterizing needs sharp ONCE (not a project dependency):
//   npm install --no-save sharp && node scripts/generate-icons.mjs
//
// Colors mirror the app.css tokens (accent #0e6e5a, ink #26251f).
// ---------------------------------------------------------------------------

import { writeFileSync, mkdirSync } from 'node:fs';

/* The artwork: white sheet with a dog-ear and text lines on emerald. */
const ART = `
  <path d="M21 11 H37 L46 20 V50 Q46 53 43 53 H21 Q18 53 18 50 V14 Q18 11 21 11 Z" fill="#ffffff"/>
  <path d="M37 11 L46 20 H39 Q37 20 37 18 Z" fill="#c7dcd4"/>
  <rect x="23" y="25" width="13" height="4" rx="2" fill="#26251f"/>
  <rect x="23" y="33" width="18" height="3" rx="1.5" fill="#0e6e5a"/>
  <rect x="23" y="39" width="15" height="3" rx="1.5" fill="#0e6e5a"/>
  <rect x="23" y="45" width="17" height="3" rx="1.5" fill="#0e6e5a"/>`;

const roundedIcon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <!-- Simplex app icon — "Papier & Tinte": ink-blue ground, white sheet.
       Generated by scripts/generate-icons.mjs — edit THERE, not here. -->
  <rect width="64" height="64" rx="14" fill="#0e6e5a"/>${ART}
</svg>
`;

/* Maskable: full-bleed background (the OS cuts its own shape), artwork
   scaled into the central safe zone. */
const maskableIcon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" fill="#0e6e5a"/>
  <g transform="translate(6.4 6.4) scale(0.8)">${ART}
  </g>
</svg>
`;

const { default: sharp } = await import('sharp').catch(() => {
  console.error('sharp fehlt — einmalig installieren: npm install --no-save sharp');
  process.exit(1);
});

mkdirSync('public/icons', { recursive: true });
writeFileSync('public/icon.svg', roundedIcon);

const render = (svg, size, file) =>
  sharp(Buffer.from(svg), { density: 300 })
    .resize(size, size)
    .png()
    .toFile(file)
    .then(() => console.log(`geschrieben: ${file} (${size}×${size})`));

await render(roundedIcon, 192, 'public/icons/icon-192.png');
await render(roundedIcon, 512, 'public/icons/icon-512.png');
await render(maskableIcon, 512, 'public/icons/icon-maskable-512.png');
console.log('geschrieben: public/icon.svg');
